# docker-compose file for postgresql
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/data/biblio-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
